---
  - name: Configure Jenkins Build Server
    hosts: control
    connection: local
    become: yes
    vars:
      java: openjdk-11-jre
      jenkins:
        apt-key-url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
        repo-url: deb http://pkg.jenkins.io/debian-stable binary/
 
    tasks:  
      - name: apt-update
        apt:
          force_apt_get: yes
          upgrade: yes

      - name: install-java
        apt:
          name: "{{java}}"

      - name: get-jenkins-apt-key
        apt_key:
          url: "{{jenkins['apt-key-url']}}"
          state: present

      - name: configure-jenkins-package-repo
        apt_repository:
          repo: "{{jenkins['repo-url']}}"
          filename: 'jenkins'
          state: present
          
      - name: apt-update
        apt:
          force_apt_get: yes
          upgrade: yes

      - name: install-jenkins
        apt:
          name: jenkins
          state: present    
          update_cache: yes
        notify: 
          - jenkins-start
      
    handlers:
      - name: jenkins-start
        service:
          name: jenkins
          enabled: yes
          state: started
