---
- hosts: control
  become: true
  
  tasks:
    - name: apt-update
      apt:
        force_apt_get: yes
        upgrade: yes

    - name: Ensure gpp key is imported
      apt_key:
        url: https://pkg.jenkins.io/debian/jenkins.io-2023.key
        state: present

    - name: Ensure Jenkins repository is added
      apt_repository:
        repo: deb [trusted=yes] https://pkg.jenkins.io/debian binary/
        state: present

    - name: Move foo to bar
      command: mv /etc/apt/sources.list.d/pkg_jenkins_io_debian_stable.list /etc/apt/sources.list.d/jenkins.list
    
    - name: Ensure Jenkins and java-devel package installed
      apt:
        name: "{{item}}"
        state: present
        update_cache: true
      loop:
        - openjdk-11-jre
        - jenkins

    - name: Ensure systemd daemon reloaded
      command: systemctl daemon-reload
    
    - name: Ensure Jenkins service is enabled and started
      service:
        name: jenkins
        state: started
    
    - name: Ensure jenkins service added to firewalld
      firewalld:
        service: jenkins
        state: enabled
        permanent: yes
        immediate: yes
